# Generated by Django 4.1.3 on 2024-04-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_menu_delete_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
